### ISSUE TITLE
求组，ts类型报错，百度很久都没有解决

### ISSUE THREAD

**Issue by zx2022x** [jzfai/vue3-admin-ts#13]
为什么总是显示 
![image](https://user-images.githubusercontent.com/99122927/179544819-8f0a1b0a-36a3-4c6f-bdaa-061f86170abb.png)

**Comment by jzfai** [comment]
请自己写个interface，或者直接去掉，用ts的类型推导

**Comment by zx2022x** [comment]
试过了就是在script中不行，其他地方是正常的。请问该项目的echart 什么时候加上去呢？？。感谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 下午4:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jzfai/vue3-admin-ts] 求组，ts类型报错，百度很久都没有解决 (Issue #13)





 
请自己写个interface，或者直接去掉，用ts的类型推导
