### ISSUE TITLE
依赖兼容问题

### ISSUE THREAD

**Issue by chengazhen** [jzfai/vue3-admin-ts#17]
作者有没有遇到过这个问题，能通过参数解决， 但是不知道作者的这个仓库为什么会有这个问题呢
![image](https://user-images.githubusercontent.com/52627267/217779446-cb893d89-36e2-43f5-8408-ad89897dd83a.png)

**Comment by chengazhen** [comment]
作者的ts好像还没有理解透彻， 关于一个数组filter 内部不需要声明类型

**Comment by jzfai** [comment]
ts学的不是很好哈
