### ISSUE TITLE
vscode中引入非.vue文件无智能提示

### ISSUE THREAD

**Issue by Sweet-KK** [jzfai/vue3-admin-ts#2]
这个问题大佬知道如何解决吗？引入json和.ts都可以  唯独.vue .js不行
![image](https://user-images.githubusercontent.com/29600932/145370807-eea07010-cb72-4521-bd2b-77aad4aaddd4.png)

**Comment by ponychoker** [comment]
检查一下 /jsconfig.json 的配置，和 /vite.config.js中：
`resolve: {
      alias: {
        '~': resolve(__dirname, './'),
        '@': resolve(__dirname, 'src')
      },
      extensions: ['.js', '.ts', '.jsx', '.tsx', '.json', '.vue', '.mjs']
    },`
是否有这项配置。vscode的其他插件或许也会导致一些提示问题

**Comment by Sweet-KK** [comment]
> 检查一下 /jsconfig.json 的配置，和 /vite.config.js中： `resolve: { alias: { '~': resolve(__dirname, './'), '@': resolve(__dirname, 'src') }, extensions: ['.js', '.ts', '.jsx', '.tsx', '.json', '.vue', '.mjs'] },` 是否有这项配置。vscode的其他插件或许也会导致一些提示问题

和这个模板的一致，extensions的注释也取消了，就是没有提示
