### ISSUE TITLE
有两个疑问

### ISSUE THREAD

**Issue by nexa-li** [jzfai/vue3-admin-ts#6]
1.支持后端获取路由，然后动态生成吗
2.有更详细的使用文档吗

**Comment by jzfai** [comment]
1.请求接口/integration-front/user/getUserInfo获取到路由信息
2.将获取到的路由信息动态拼装成架构中的路由格式（一般请求回来的路由,和架构中的不一样）
3.通过 router.addRoute(route)添加到vue-router上

**Comment by nexa-li** [comment]
多谢
