### ISSUE TITLE
这个地方是不是写错了？

### ISSUE THREAD

**Issue by 332lfgb6** [jzfai/vue3-admin-ts#7]
![图片](https://user-images.githubusercontent.com/51245335/151661682-726249cd-f5bf-4dcc-8fef-87e200ee1e47.png)
![图片](https://user-images.githubusercontent.com/51245335/151661711-9372b57f-7e90-481d-9d32-7089f8a4c7a2.png)
我打印出来的永远不可能===1

可以通过`location.href.includes('/login')`来解决。

**Comment by jzfai** [comment]
你好，这里的代码逻辑确实有点问题，下个版本会按照你的推荐进行修改
你也可以 fork 然后pull 给我进行修改

**Comment by 332lfgb6** [comment]
> 你好，这里的代码逻辑确实有点问题，下个版本会按照你的推荐进行修改 你也可以 fork 然后pull 给我进行修改

我没学过fork，你抽个空改改就行了😄

**Comment by jzfai** [comment]
已修复
